# Site settings
baseurl = "/"
title = "Dr. Daróczi Lajos kisállatrendelője"
theme = "syna"
enableGitInfo = false
version = "0.16.1"
#publishDir = "docs"

# Google Analytics tracking
googleAnalytics = "" # TODO

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Dr. Daróczi Lajos"
  description = "Dr. Daróczi Lajos kisállatrendelője"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    # favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "boxerfej 32x32.png"
    # favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Főoldal"
  weight = 10

[[menu.main]]
  url = "#rolunk"
  name = "Szolgáltatások"
  weight = 20

# [[menu.main]]
#   url = "#munkatarsak"
#   name = "Munkatársaink"
#   weight = 25

[[menu.main]]
  url = "#rendeles"
  name = "Rendelési idő"
  weight = 30

# [[menu.main]]
#   url = "#idopont"
#   name = "Időpontfoglalás"
#   weight = 35

[[menu.main]]
  url = "#gyik"
  name = "Gyakran Ismételt Kérdések"
  weight = 39

[[menu.main]]
  url = "#map"
  name = "Útvonaltervezés"
  weight = 40

[[menu.main]]
  url = "#velemenyek"
  name = "Értékelések"
  weight = 45

[[menu.main]]
  url = "#contact"
  name = "Elérhetőség"
  weight = 50

# [[menu.footer]]
#   url = "#"
#   name = "Link"
#   weight = 10

# [[menu.footer]]
#   url = "#"
#   name = "Long Link"
#   weight = 30

# [[menu.footer]]
#   url = "#"
#   name = "Tiny Link"
#   weight = 30

# [[menu.copyright_footer]]
#   url = "/about"
#   name = "About Us"
#   weight = 10

# [[menu.copyright_footer]]
#   url = "#"
#   name = "Another Link"
#   weight = 30

# [[menu.footer_social]]
#   weight = 20
#   name = "facebook"
#   pre = "fab fa-facebook-f"
#   url = "#"

# [[menu.footer_social]]
#   weight = 30
#   name = "linkedin"
#   pre = "fab fa-linkedin-in"
#   url = "#"
